export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
] as const;

export type StateCode = (typeof US_STATES)[number]["value"];

export function getStateLabel(code: string): string {
  return US_STATES.find((state) => state.value === code)?.label ?? code;
}

/** Map state codes to grant region labels used in static grant data */
export const STATE_TO_REGIONS: Record<string, string[]> = {
  TX: ["Texas", "South Central US", "National"],
  OK: ["South Central US", "National"],
  LA: ["South Central US", "National"],
  AR: ["South Central US", "National"],
  AZ: ["Southwest US", "National"],
  NM: ["Southwest US", "National"],
  CA: ["Western US", "National"],
  WA: ["Western US", "National"],
  OR: ["Western US", "National"],
  NV: ["Western US", "National"],
  CO: ["Western US", "National"],
  UT: ["Western US", "National"],
  GA: ["Southeast US", "National"],
  FL: ["Southeast US", "National"],
  NC: ["Southeast US", "National"],
  SC: ["Southeast US", "National"],
  AL: ["Southeast US", "National"],
  TN: ["Southeast US", "National"],
  IL: ["Midwest US", "National"],
  OH: ["Midwest US", "National"],
  MI: ["Midwest US", "National"],
  MN: ["Midwest US", "National"],
  MO: ["Midwest US", "National"],
  WI: ["Midwest US", "National"],
  NY: ["Northeast US", "National"],
  MA: ["Northeast US", "National"],
  PA: ["Northeast US", "National"],
  NJ: ["Northeast US", "National"],
  CT: ["Northeast US", "National"],
};

export function getRegionsForState(state?: string | null): string[] {
  if (!state) return ["National"];
  return STATE_TO_REGIONS[state.toUpperCase()] ?? ["National"];
}
